#指定项目的运行环境,可自动启用或停止某些功能
spring:
  profiles:
    active: prod

http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true


#tomcat config
server:
  port: 80
  session:
    timeout: 30

#mybatis config
mybatis:
  type-aliases-package: com.icec.modal

# 微信配置
token: icec